[workspace]
resolver = "2"
members = [
    "ssh-cipher",
    "ssh-derive",
    "ssh-encoding",
    "ssh-key",
    "ssh-protocol",
]

[profile.dev]
opt-level = 2

[patch.crates-io]
ssh-cipher = { path = "./ssh-cipher" }
ssh-derive = { path = "./ssh-derive" }
ssh-encoding = { path = "./ssh-encoding" }
ssh-key = { path = "./ssh-key" }

# https://github.com/dalek-cryptography/curve25519-dalek/pull/676
#ed25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek.git", branch = "rustcrypto-new-releases" }
