[workspace]
resolver = "2"
members = [
    "ssh-cipher",
    "ssh-derive",
    "ssh-encoding",
    "ssh-key",
    "ssh-protocol",
]

[profile.dev]
opt-level = 2

[patch.crates-io]
ssh-cipher = { path = "./ssh-cipher" }
ssh-derive = { path = "./ssh-derive" }
ssh-encoding = { path = "./ssh-encoding" }
ssh-key = { path = "./ssh-key" }

ed25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", branch = "rand_core/v0.10-rc" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits" }
ff = { git = "https://github.com/tarcieri/ff", branch = "rand_core/v0.10.0-rc-2" }
group = { git = "https://github.com/tarcieri/group", branch = "rand_core/v0.10.0-rc-2" }
p256 = { git = "https://github.com/RustCrypto/elliptic-curves" }
p384 = { git = "https://github.com/RustCrypto/elliptic-curves" }
p521 = { git = "https://github.com/RustCrypto/elliptic-curves" }
primefield = { git = "https://github.com/RustCrypto/elliptic-curves " }
